version: '3.9'
services:
  db:
    image: postgres:12
    user: postgres
    ports:
      - '5432:5432'
    profiles: ['test']
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accounting_test
